apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-node-app
  template:
    metadata:
      labels:
        app: cicd-node-app
    spec:
      containers:
      - name: node-app
        image: yourdockerhubusername/cicd-node-app:latest
        ports:
        - containerPort: 3000
