apiVersion: v1
kind: Service
metadata:
  name: cicd-node-service
spec:
  type: NodePort
  selector:
    app: cicd-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
